### ISSUE TITLE
the bigger crafting table doesn't like "null"s

### ISSUE THREAD

**Issue by Boter316** [WanionCane/BiggerCraftingTables#1]
the tables like to get very finicky when I add "nulls" in the place of items, my script is

mods.biggercraftingtables.Big.addShaped(<customthings:true_nights_edgeSword>, [
[NeuiS, TrueS, null, TrueS, NeuiS],
[TrueS, null, <customthings:nights_edgeSword>, null, TrueS],
[null, Admin, <customthings:item:22>, Admin, null],
[TrueS, null, <customthings:nights_edgeSword>, null, TrueS],
[NeuiS, TrueS, null, TrueS, NeuiS]
]);

and the result is 
![2016-12-31_16 52 54](https://cloud.githubusercontent.com/assets/19333748/21579828/9e95c6b0-cf79-11e6-98b8-8c517111e1e7.png)

I do hope you can fix this, I added this mod to my pack for the option of a bigger than normal table but smaller than dire tables, but it does not seem to want to function properly

**Comment by Boter316** [comment]
it should look like 
![2016-12-31_16 55 00](https://cloud.githubusercontent.com/assets/19333748/21579830/e601d976-cf79-11e6-9785-c7942e55421d.png)

**Comment by Boter316** [comment]
the singularity changes colors, so don't worry about that bit, so does the star

**Comment by WanionCane** [comment]
thanks for the report and for the screenshots, as soon as possible I will fix this.

**Comment by WanionCane** [comment]
I hope [this](https://minecraft.curseforge.com/projects/bigger-crafting-tables/files/2363210) fix your issue, if it doesn't, feel free to re-open the issue ^^

**Comment by Boter316** [comment]
apparently it's not fixed :/ sorry for taking so long to get back to you but here's what should be

![2017-03-21_21 55 49](https://cloud.githubusercontent.com/assets/19333748/24182773/38c2c3be-0e81-11e7-8d6d-8f07e2e1c837.png)
and the script:
mods.biggercraftingtables.Big.addShaped(<customnpcs:npcBronzeHalberd>, [
	[null, null, Bronze, Bronze, null],
	[null, Bronze, Stick, Bronze, null],
	[null, null, Stick, Bronze, null],
	[null, null, Stick, null, null],
	[null, null, Stick, null, null]
]);

and here's what the recipe shows
![2017-03-21_21 57 04](https://cloud.githubusercontent.com/assets/19333748/24182794/5b236800-0e81-11e7-95a4-871c60652a18.png)
also, doing either the recipe I coded or the one that shows results in no item being produced, for some reason though this works

![2017-03-21_21 58 28](https://cloud.githubusercontent.com/assets/19333748/24182818/8e2a5556-0e81-11e7-8eab-cb59ca07fa13.png)
mods.biggercraftingtables.Big.addShaped(<customnpcs:npcBronzeBattleAxe>, [
	[null, Bronze, Stick, Bronze, null],
	[Bronze, Stick, Stick, Stick, Bronze],
	[null, Bronze, Stick, Bronze, null],
	[null, null, Stick, null, null],
	[null, null, Stick, null, null]
]);

**Comment by Boter316** [comment]
don't worry about differences in the ingots, it's the oredictionary, confirmed they (should have) worked with the one that worked

**Comment by WanionCane** [comment]
omg... not again XD
so, could you try with this?

[null, Bronze, Bronze],
[Bronze, Stick, Bronze],
[null, Stick, Bronze],
[null, Stick, null],
[null, Stick, null]

idk if MineTweaker supports this, but Bigger Crafting tables supports it, just for curiosity reasons.

**Comment by Boter316** [comment]
that does work

**Comment by WanionCane** [comment]
works? yay!

**Comment by Boter316** [comment]
I appreciate you taking the time to look into these things, I like having your mod in my pack, I have a mod that has a 4/4 crafting grid but it doesn't have an nei hookup so you don't know the items are even craftable, so the 5/5 works nicely, and I love that I'm able to halt the dire table crafting until you have the other two, makes for a good thing when I'm trying to tier progression in the pack

**Comment by WanionCane** [comment]
so, thanks again for helping me with this, I found the bug, was just one variable that was wrong... =/
a fix for this will be released soon, along with many new features =D

**Comment by Boter316** [comment]
no problem, I thoroughly test everything before I use it for leisure,
I have a lot of resources and can test anything, and the pack I'm working on that plans to include it has enough mods that all compatibility of every mod ever is essentially tested with this modpack's existence (lol)
also yes, have a dedicated server and a number of beta testers to work with, so if you have anything you'd like tested I can and am currently do so
