### ISSUE TITLE
[1.12.2] Scary bug with Item conduit and your auto crafting tables (big version)

### ISSUE THREAD

**Issue by TheSnowyChickens** [WanionCane/BiggerCraftingTables#10]
MC: 1.12.2
BCT: 1.8
WL: 1.9
Forge: 2775

On a Server, a user create a auto crafting for a custom crafting recipe. (ME Controller)
![2018-11-25_01 54 07](https://user-images.githubusercontent.com/29357962/48974308-1fba7580-f055-11e8-9e10-f9137c36b65d.png)
![2018-11-25_01 55 07](https://user-images.githubusercontent.com/29357962/48974309-2648ed00-f055-11e8-951c-0ad7dcad19de.png)
![2018-11-25_01 55 30](https://user-images.githubusercontent.com/29357962/48974315-3cef4400-f055-11e8-9559-04fb323ec68b.png)

So, with the Ender IO item conduits he can take out "infinite" recipe outputs.
(depending on the amount of items, that the Ender IO extraction speed upgrade can pull)

**Comment by WanionCane** [comment]
this will be fixed in the next version =)

**Comment by WanionCane** [comment]
[done](https://minecraft.curseforge.com/projects/bigger-crafting-tables/files/2641629) =P

**Comment by TheSnowyChickens** [comment]
Nice, thx
