### ISSUE TITLE
Help with adding recipies

### ISSUE THREAD

**Issue by duhadventure** [WanionCane/BiggerCraftingTables#2]
![](https://cdn.discordapp.com/attachments/336704401970561025/337000059491188736/Diamond_Boots.png)
I am attempting to add the above recipie

//values
val diamond = <minecraft:diamond>;

//Shaped recipes
recipes.remove(<minecraft:diamond_boots>);

//5x5 recipies
mods.biggercraftingtables.Big.addShaped(diamond_boots * 1,[[diamond,diamond,null,diamond,diamond],[diamond,diamond,null,diamond,diamond],[diamond,diamond,null,diamond,diamond],[null,null,null,null,null],[null,null,null,null,null]]);
^^^
That is what i have in minetweaker so far, but since there is no documentation I could find for 5x5 or 7x7 crafting tables I don't know if this is right.

Upon attempting to reload the script I get this error: https://pastebin.com/w7EL4Cqz

**Comment by WanionCane** [comment]
you can try

```
//values
val diamond = <minecraft:diamond>;

//Shaped recipes
recipes.remove(<minecraft:diamond_boots>);

//5x5 recipies
mods.biggercraftingtables.Big.addShaped(<minecraft:diamond_boots>,[[diamond,diamond,null,diamond,diamond],[diamond,diamond,null,diamond,diamond],[diamond,diamond,null,diamond,diamond],[null,null,null,null,null],[null,null,null,null,null]]);
```

I hope only this is enough to make it work.

**Comment by duhadventure** [comment]
TY that worked. What would a 7*7 blank template look like?

**Comment by WanionCane** [comment]
yay!
about the 7x7 pattern, it should looks like this
`
mods.biggercraftingtables.Huge.addShaped(<minecraft:diamond_boots>,[[null,null,null,null,null,null,null],[null,null,null,null,null,null,null],[null,null,null,null,null,null,null],[null,null,null,null,null,null,null],[null,null,null,null,null,null,null],[null,null,null,null,null,null,null],[null,null,null,null,null,null,null]]);
`
