### ISSUE TITLE
(SSP/SMP) Crash or Internal server error when opening crafting table

### ISSUE THREAD

**Issue by duhadventure** [WanionCane/BiggerCraftingTables#3]
When using Big Crafting table, recipes show up in NEI but when attempting to craft it will crash you in Singleplayer and Multiplayer (If client Does not have script) and if they do it Internal server errors you,
Singleplayer crash occurs when crafting, MP when trying to open table.  Huge table crashes you while you are putting ingredients in, usually you can get most in before crash.

Script Used:
https://pastebin.com/HJNFy516

Singleplayer Crash: 
Big Table: https://pastebin.com/Ye9JYZNy
Huge table: https://pastebin.com/6FmDUt1A

Multiplayer Crash:
Big Table: https://pastebin.com/XgHUnT13
Crashes while usingHuge Table in middle of recipe: https://pastebin.com/xKXrbVXb

**Comment by WanionCane** [comment]
sorry for this late answer, been awhile since I don't work on this mod, so, I will take a look on this soon.

**Comment by WanionCane** [comment]
sorry for the delay, could you try this? [BiggerCraftingTables-1.7.10-1.6.jar](https://minecraft.curseforge.com/projects/bigger-crafting-tables/files/2510301)
