### ISSUE TITLE
[1.12.2] Recipes don't appear in JEI

### ISSUE THREAD

**Issue by JohnC94** [WanionCane/BiggerCraftingTables#6]
Added a few 5x5 and a few 7x7 recipes and neither appear in JEI. I can craft them so I know they are valid recipes.

Forge: 14.23.2.2619
Bigger Crafting Tables: 1.12.2-1.0

Modlist: https://i.imgur.com/H78y8Sw.png

**Comment by WanionCane** [comment]
coming soon :laughing:

**Comment by HurtsAsHell** [comment]
Please, add the recipes in JEI

**Comment by WanionCane** [comment]
sorry for the delay guys.
