### ISSUE TITLE
Classes registered twice

### ISSUE THREAD

**Issue by Maxwelljones** [WanionCane/BiggerCraftingTables#9]
Hello!

I realized I am having an error as you registered your classes twice.

Issue Description:
ERROR: system: Huge is already defined in that package
ERROR: system: Big is already defined in that package

Most recent log file where the issue was present:
https://pastebin.com/FrFKkgWK

Affected Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2768
Using a server: no

Reference: https://github.com/CraftTweaker/CraftTweaker/issues/663

**Comment by Maxwelljones** [comment]
Thank you for being so responsive!! <3

I guess I can close the issue? This will be sorted in the next version if I do understand correctly?

**Comment by WanionCane** [comment]
you are welcome =D

the fixed version is already out, [checkout](https://minecraft.curseforge.com/projects/bigger-crafting-tables/files/2633934)
I tried here, and it is working fine =P

**Comment by Maxwelljones** [comment]
Works like a charm, thanks =)
